@extends('layouts.admin')
@section('title', 'Institutions')
@section('content')
<x-admin.page-header title="Institutions" description="Manage education institution contact profiles." icon="I" eyebrow="Business profiles">
@can('institutions.manage')<a class="egh-button" href="{{ route('admin.institutions.create') }}">Create Institution</a>@endcan
</x-admin.page-header>
<form method="GET" class="egh-card ins-filter"><input name="search" value="{{ $filters['search'] }}" placeholder="Name, email or registration"><select name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected($filters['status'] === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="egh-button">Filter</button></form>
<div class="egh-card admin-table-card"><table class="ins-table"><thead><tr><th>Name</th><th>Contact</th><th>Registration</th><th>Country</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($institutions as $institution)<tr><td>{{ $institution->name }}</td><td>{{ $institution->email ?: '—' }}@if($institution->phone)<br><span class="ins-muted">{{ $institution->phone }}</span>@endif</td><td>{{ $institution->registration_number ?: '—' }}</td><td>{{ $institution->country ? $institution->country->name.' ('.$institution->country->iso2.')' : '—' }}</td><td>{{ ucfirst($institution->status) }}</td><td><a class="ins-link" href="{{ route('admin.institutions.show', $institution) }}">View</a>@can('institutions.manage') · <a class="ins-link" href="{{ route('admin.institutions.edit', $institution) }}">Edit</a>@endcan</td></tr>@empty<tr><td colspan="6">No institutions found.</td></tr>@endforelse</tbody></table></div>@if ($institutions->hasPages())<div class="admin-pagination">{{ $institutions->links() }}</div>@endif
@endsection
