@extends('layouts.admin')
@section('title', 'Students')
@section('content')
<style>.stu-head{display:flex;justify-content:space-between;gap:16px;margin-bottom:18px}.stu-muted{color:#64748b}.stu-filter{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}.stu-filter input,.stu-filter select{border:1px solid #cbd5e1;border-radius:8px;padding:9px}.stu-table{width:100%;border-collapse:collapse;font-size:14px}.stu-table th,.stu-table td{padding:11px 8px;border-bottom:1px solid #e5e7eb;text-align:left}.stu-table th{font-size:12px;text-transform:uppercase;color:#64748b}.stu-link{color:#244fc7;text-decoration:none;font-weight:600}</style>
<div class="stu-head"><div><h1 style="margin:0">Students</h1><p class="stu-muted">Manage private operational student profiles.</p></div>@can('students.manage')<a class="egh-button" href="{{ route('admin.students.create') }}">Create Student</a>@endcan</div>
<form method="GET" class="egh-card stu-filter"><input name="search" value="{{ $filters['search'] }}" placeholder="Name, email or reference"><select name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected($filters['status'] === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="egh-button">Filter</button></form>
<div class="egh-card" style="overflow:auto"><table class="stu-table"><thead><tr><th>Reference</th><th>Name</th><th>Contact</th><th>Country</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($students as $student)<tr><td>{{ $student->reference_code }}</td><td>{{ $student->first_name }} {{ $student->last_name }}</td><td>{{ $student->email }}@if($student->phone)<br><span class="stu-muted">{{ $student->phone }}</span>@endif</td><td>{{ $student->country ? $student->country->name.' ('.$student->country->iso2.')' : '—' }}</td><td>{{ ucfirst($student->status) }}</td><td><a class="stu-link" href="{{ route('admin.students.show', $student) }}">View</a>@can('students.manage') · <a class="stu-link" href="{{ route('admin.students.edit', $student) }}">Edit</a>@endcan</td></tr>@empty<tr><td colspan="6">No students found.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:16px">{{ $students->links() }}</div>
@endsection
