@extends('layouts.admin')
@section('title', 'Affiliates')
@section('content')
<style>.af-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.af-muted{color:#64748b}.af-filter{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}.af-filter input,.af-filter select{border:1px solid #cbd5e1;border-radius:8px;padding:9px;background:#fff}.af-table{width:100%;border-collapse:collapse;font-size:14px}.af-table th,.af-table td{padding:11px 8px;border-bottom:1px solid #e5e7eb;text-align:left}.af-table th{color:#64748b;text-transform:uppercase;font-size:12px}.af-link{color:#244fc7;text-decoration:none;font-weight:600}</style>
<div class="af-head"><div><h1 style="margin:0">Affiliates</h1><p class="af-muted">Manage affiliate partner profiles and referral identifiers.</p></div>@can('affiliates.manage')<a class="egh-button" href="{{ route('admin.affiliates.create') }}">Create Affiliate</a>@endcan</div>
<form method="GET" class="egh-card af-filter"><input name="search" value="{{ $filters['search'] }}" placeholder="Name, email, organization or code"><select name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected($filters['status'] === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="egh-button">Filter</button></form>
<div class="egh-card" style="overflow:auto"><table class="af-table"><thead><tr><th>Name</th><th>Contact</th><th>Organization</th><th>Referral code</th><th>Country</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($affiliates as $affiliate)<tr><td>{{ $affiliate->name }}</td><td>{{ $affiliate->email }}@if($affiliate->phone)<br><span class="af-muted">{{ $affiliate->phone }}</span>@endif</td><td>{{ $affiliate->organization_name ?: '—' }}</td><td>{{ $affiliate->referral_code }}</td><td>{{ $affiliate->country ? $affiliate->country->name.' ('.$affiliate->country->iso2.')' : '—' }}</td><td>{{ ucfirst($affiliate->status) }}</td><td><a class="af-link" href="{{ route('admin.affiliates.show', $affiliate) }}">View</a>@can('affiliates.manage') · <a class="af-link" href="{{ route('admin.affiliates.edit', $affiliate) }}">Edit</a>@endcan</td></tr>@empty<tr><td colspan="7">No affiliates found.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:16px">{{ $affiliates->links() }}</div>
@endsection
